apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: react-chart
    meta.helm.sh/release-namespace: default
  name: react-chart
  namespace: react-nginx
  labels:
    app: test
    app.kubernetes.io/instance: react-chart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: react-chart
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: react-chart-0.1.0
    job: monitor
spec:
  selector:
    app.kubernetes.io/instance: react-chart
    app.kubernetes.io/name: react-chart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      protocol: TCP
      targetPort: 9113   
